/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardroutesIndexRouteImport } from './routes/dashboard/(routes)/index'
import { Route as DashboardroutesChartsRouteImport } from './routes/dashboard/(routes)/charts'
import { Route as DashboardroutesBrochureTypesRouteImport } from './routes/dashboard/(routes)/brochure-types'
import { Route as authroutesResetPasswordRouteImport } from './routes/(auth)/(routes)/reset-password'
import { Route as authroutesLoginRouteImport } from './routes/(auth)/(routes)/login'
import { Route as authroutesForgotPasswordRouteImport } from './routes/(auth)/(routes)/forgot-password'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardroutesIndexRoute = DashboardroutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesChartsRoute = DashboardroutesChartsRouteImport.update({
  id: '/(routes)/charts',
  path: '/charts',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesBrochureTypesRoute =
  DashboardroutesBrochureTypesRouteImport.update({
    id: '/(routes)/brochure-types',
    path: '/brochure-types',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const authroutesResetPasswordRoute = authroutesResetPasswordRouteImport.update({
  id: '/(routes)/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesLoginRoute = authroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesForgotPasswordRoute =
  authroutesForgotPasswordRouteImport.update({
    id: '/(routes)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/brochure-types': typeof DashboardroutesBrochureTypesRoute
  '/dashboard/charts': typeof DashboardroutesChartsRoute
  '/dashboard/': typeof DashboardroutesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/brochure-types': typeof DashboardroutesBrochureTypesRoute
  '/dashboard/charts': typeof DashboardroutesChartsRoute
  '/dashboard': typeof DashboardroutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(auth)/(routes)/forgot-password': typeof authroutesForgotPasswordRoute
  '/(auth)/(routes)/login': typeof authroutesLoginRoute
  '/(auth)/(routes)/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/(routes)/brochure-types': typeof DashboardroutesBrochureTypesRoute
  '/dashboard/(routes)/charts': typeof DashboardroutesChartsRoute
  '/dashboard/(routes)/': typeof DashboardroutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/brochure-types'
    | '/dashboard/charts'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/brochure-types'
    | '/dashboard/charts'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/(auth)/(routes)/forgot-password'
    | '/(auth)/(routes)/login'
    | '/(auth)/(routes)/reset-password'
    | '/dashboard/(routes)/brochure-types'
    | '/dashboard/(routes)/charts'
    | '/dashboard/(routes)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/(routes)/': {
      id: '/dashboard/(routes)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardroutesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/charts': {
      id: '/dashboard/(routes)/charts'
      path: '/charts'
      fullPath: '/dashboard/charts'
      preLoaderRoute: typeof DashboardroutesChartsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/brochure-types': {
      id: '/dashboard/(routes)/brochure-types'
      path: '/brochure-types'
      fullPath: '/dashboard/brochure-types'
      preLoaderRoute: typeof DashboardroutesBrochureTypesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/(routes)/reset-password': {
      id: '/(auth)/(routes)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authroutesResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/login': {
      id: '/(auth)/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authroutesLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/forgot-password': {
      id: '/(auth)/(routes)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authroutesForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authroutesForgotPasswordRoute: typeof authroutesForgotPasswordRoute
  authroutesLoginRoute: typeof authroutesLoginRoute
  authroutesResetPasswordRoute: typeof authroutesResetPasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authroutesForgotPasswordRoute: authroutesForgotPasswordRoute,
  authroutesLoginRoute: authroutesLoginRoute,
  authroutesResetPasswordRoute: authroutesResetPasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardroutesBrochureTypesRoute: typeof DashboardroutesBrochureTypesRoute
  DashboardroutesChartsRoute: typeof DashboardroutesChartsRoute
  DashboardroutesIndexRoute: typeof DashboardroutesIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardroutesBrochureTypesRoute: DashboardroutesBrochureTypesRoute,
  DashboardroutesChartsRoute: DashboardroutesChartsRoute,
  DashboardroutesIndexRoute: DashboardroutesIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
