/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChartsSectorIdRouteImport } from './routes/charts/$sectorId'
import { Route as DashboardroutesIndexRouteImport } from './routes/dashboard/(routes)/index'
import { Route as DashboardroutesWarehousesRouteImport } from './routes/dashboard/(routes)/warehouses'
import { Route as DashboardroutesUsersRouteImport } from './routes/dashboard/(routes)/users'
import { Route as DashboardroutesSettingsRouteImport } from './routes/dashboard/(routes)/settings'
import { Route as DashboardroutesReportsRouteImport } from './routes/dashboard/(routes)/reports'
import { Route as DashboardroutesLocationsRouteImport } from './routes/dashboard/(routes)/locations'
import { Route as DashboardroutesCustomersRouteImport } from './routes/dashboard/(routes)/customers'
import { Route as DashboardroutesBrochureTypesRouteImport } from './routes/dashboard/(routes)/brochure-types'
import { Route as DashboardroutesBrochureRouteImport } from './routes/dashboard/(routes)/brochure'
import { Route as authroutesResetPasswordRouteImport } from './routes/(auth)/(routes)/reset-password'
import { Route as authroutesLoginRouteImport } from './routes/(auth)/(routes)/login'
import { Route as authroutesForgotPasswordRouteImport } from './routes/(auth)/(routes)/forgot-password'
import { Route as DashboardroutesInventoryIndexRouteImport } from './routes/dashboard/(routes)/inventory/index'
import { Route as DashboardroutesChartsIndexRouteImport } from './routes/dashboard/(routes)/charts/index'
import { Route as DashboardroutesInventoryNewRouteImport } from './routes/dashboard/(routes)/inventory/new'
import { Route as DashboardroutesInventoryMonthEndCountsRouteImport } from './routes/dashboard/(routes)/inventory/month-end-counts'
import { Route as DashboardroutesInventoryIntakeRequestRouteImport } from './routes/dashboard/(routes)/inventory/intake-request'
import { Route as DashboardroutesInventoryIdRouteImport } from './routes/dashboard/(routes)/inventory/$id'
import { Route as DashboardroutesInventoryRequestQueueIndexRouteImport } from './routes/dashboard/(routes)/inventory/request-queue.index'
import { Route as DashboardroutesInventoryRequestQueueIdRouteImport } from './routes/dashboard/(routes)/inventory/request-queue.$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsSectorIdRoute = ChartsSectorIdRouteImport.update({
  id: '/charts/$sectorId',
  path: '/charts/$sectorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardroutesIndexRoute = DashboardroutesIndexRouteImport.update({
  id: '/(routes)/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesWarehousesRoute =
  DashboardroutesWarehousesRouteImport.update({
    id: '/(routes)/warehouses',
    path: '/warehouses',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesUsersRoute = DashboardroutesUsersRouteImport.update({
  id: '/(routes)/users',
  path: '/users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesSettingsRoute = DashboardroutesSettingsRouteImport.update({
  id: '/(routes)/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesReportsRoute = DashboardroutesReportsRouteImport.update({
  id: '/(routes)/reports',
  path: '/reports',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardroutesLocationsRoute =
  DashboardroutesLocationsRouteImport.update({
    id: '/(routes)/locations',
    path: '/locations',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesCustomersRoute =
  DashboardroutesCustomersRouteImport.update({
    id: '/(routes)/customers',
    path: '/customers',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesBrochureTypesRoute =
  DashboardroutesBrochureTypesRouteImport.update({
    id: '/(routes)/brochure-types',
    path: '/brochure-types',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesBrochureRoute = DashboardroutesBrochureRouteImport.update({
  id: '/(routes)/brochure',
  path: '/brochure',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authroutesResetPasswordRoute = authroutesResetPasswordRouteImport.update({
  id: '/(routes)/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesLoginRoute = authroutesLoginRouteImport.update({
  id: '/(routes)/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const authroutesForgotPasswordRoute =
  authroutesForgotPasswordRouteImport.update({
    id: '/(routes)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => authRouteRoute,
  } as any)
const DashboardroutesInventoryIndexRoute =
  DashboardroutesInventoryIndexRouteImport.update({
    id: '/(routes)/inventory/',
    path: '/inventory/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesChartsIndexRoute =
  DashboardroutesChartsIndexRouteImport.update({
    id: '/(routes)/charts/',
    path: '/charts/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesInventoryNewRoute =
  DashboardroutesInventoryNewRouteImport.update({
    id: '/(routes)/inventory/new',
    path: '/inventory/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesInventoryMonthEndCountsRoute =
  DashboardroutesInventoryMonthEndCountsRouteImport.update({
    id: '/(routes)/inventory/month-end-counts',
    path: '/inventory/month-end-counts',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesInventoryIntakeRequestRoute =
  DashboardroutesInventoryIntakeRequestRouteImport.update({
    id: '/(routes)/inventory/intake-request',
    path: '/inventory/intake-request',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesInventoryIdRoute =
  DashboardroutesInventoryIdRouteImport.update({
    id: '/(routes)/inventory/$id',
    path: '/inventory/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesInventoryRequestQueueIndexRoute =
  DashboardroutesInventoryRequestQueueIndexRouteImport.update({
    id: '/(routes)/inventory/request-queue/',
    path: '/inventory/request-queue/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardroutesInventoryRequestQueueIdRoute =
  DashboardroutesInventoryRequestQueueIdRouteImport.update({
    id: '/(routes)/inventory/request-queue/$id',
    path: '/inventory/request-queue/$id',
    getParentRoute: () => DashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/charts/$sectorId': typeof ChartsSectorIdRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/brochure': typeof DashboardroutesBrochureRoute
  '/dashboard/brochure-types': typeof DashboardroutesBrochureTypesRoute
  '/dashboard/customers': typeof DashboardroutesCustomersRoute
  '/dashboard/locations': typeof DashboardroutesLocationsRoute
  '/dashboard/reports': typeof DashboardroutesReportsRoute
  '/dashboard/settings': typeof DashboardroutesSettingsRoute
  '/dashboard/users': typeof DashboardroutesUsersRoute
  '/dashboard/warehouses': typeof DashboardroutesWarehousesRoute
  '/dashboard/': typeof DashboardroutesIndexRoute
  '/dashboard/inventory/$id': typeof DashboardroutesInventoryIdRoute
  '/dashboard/inventory/intake-request': typeof DashboardroutesInventoryIntakeRequestRoute
  '/dashboard/inventory/month-end-counts': typeof DashboardroutesInventoryMonthEndCountsRoute
  '/dashboard/inventory/new': typeof DashboardroutesInventoryNewRoute
  '/dashboard/charts/': typeof DashboardroutesChartsIndexRoute
  '/dashboard/inventory/': typeof DashboardroutesInventoryIndexRoute
  '/dashboard/inventory/request-queue/$id': typeof DashboardroutesInventoryRequestQueueIdRoute
  '/dashboard/inventory/request-queue/': typeof DashboardroutesInventoryRequestQueueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/charts/$sectorId': typeof ChartsSectorIdRoute
  '/forgot-password': typeof authroutesForgotPasswordRoute
  '/login': typeof authroutesLoginRoute
  '/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/brochure': typeof DashboardroutesBrochureRoute
  '/dashboard/brochure-types': typeof DashboardroutesBrochureTypesRoute
  '/dashboard/customers': typeof DashboardroutesCustomersRoute
  '/dashboard/locations': typeof DashboardroutesLocationsRoute
  '/dashboard/reports': typeof DashboardroutesReportsRoute
  '/dashboard/settings': typeof DashboardroutesSettingsRoute
  '/dashboard/users': typeof DashboardroutesUsersRoute
  '/dashboard/warehouses': typeof DashboardroutesWarehousesRoute
  '/dashboard': typeof DashboardroutesIndexRoute
  '/dashboard/inventory/$id': typeof DashboardroutesInventoryIdRoute
  '/dashboard/inventory/intake-request': typeof DashboardroutesInventoryIntakeRequestRoute
  '/dashboard/inventory/month-end-counts': typeof DashboardroutesInventoryMonthEndCountsRoute
  '/dashboard/inventory/new': typeof DashboardroutesInventoryNewRoute
  '/dashboard/charts': typeof DashboardroutesChartsIndexRoute
  '/dashboard/inventory': typeof DashboardroutesInventoryIndexRoute
  '/dashboard/inventory/request-queue/$id': typeof DashboardroutesInventoryRequestQueueIdRoute
  '/dashboard/inventory/request-queue': typeof DashboardroutesInventoryRequestQueueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/charts/$sectorId': typeof ChartsSectorIdRoute
  '/(auth)/(routes)/forgot-password': typeof authroutesForgotPasswordRoute
  '/(auth)/(routes)/login': typeof authroutesLoginRoute
  '/(auth)/(routes)/reset-password': typeof authroutesResetPasswordRoute
  '/dashboard/(routes)/brochure': typeof DashboardroutesBrochureRoute
  '/dashboard/(routes)/brochure-types': typeof DashboardroutesBrochureTypesRoute
  '/dashboard/(routes)/customers': typeof DashboardroutesCustomersRoute
  '/dashboard/(routes)/locations': typeof DashboardroutesLocationsRoute
  '/dashboard/(routes)/reports': typeof DashboardroutesReportsRoute
  '/dashboard/(routes)/settings': typeof DashboardroutesSettingsRoute
  '/dashboard/(routes)/users': typeof DashboardroutesUsersRoute
  '/dashboard/(routes)/warehouses': typeof DashboardroutesWarehousesRoute
  '/dashboard/(routes)/': typeof DashboardroutesIndexRoute
  '/dashboard/(routes)/inventory/$id': typeof DashboardroutesInventoryIdRoute
  '/dashboard/(routes)/inventory/intake-request': typeof DashboardroutesInventoryIntakeRequestRoute
  '/dashboard/(routes)/inventory/month-end-counts': typeof DashboardroutesInventoryMonthEndCountsRoute
  '/dashboard/(routes)/inventory/new': typeof DashboardroutesInventoryNewRoute
  '/dashboard/(routes)/charts/': typeof DashboardroutesChartsIndexRoute
  '/dashboard/(routes)/inventory/': typeof DashboardroutesInventoryIndexRoute
  '/dashboard/(routes)/inventory/request-queue/$id': typeof DashboardroutesInventoryRequestQueueIdRoute
  '/dashboard/(routes)/inventory/request-queue/': typeof DashboardroutesInventoryRequestQueueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/charts/$sectorId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/brochure'
    | '/dashboard/brochure-types'
    | '/dashboard/customers'
    | '/dashboard/locations'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/warehouses'
    | '/dashboard/'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/intake-request'
    | '/dashboard/inventory/month-end-counts'
    | '/dashboard/inventory/new'
    | '/dashboard/charts/'
    | '/dashboard/inventory/'
    | '/dashboard/inventory/request-queue/$id'
    | '/dashboard/inventory/request-queue/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/charts/$sectorId'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/dashboard/brochure'
    | '/dashboard/brochure-types'
    | '/dashboard/customers'
    | '/dashboard/locations'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/users'
    | '/dashboard/warehouses'
    | '/dashboard'
    | '/dashboard/inventory/$id'
    | '/dashboard/inventory/intake-request'
    | '/dashboard/inventory/month-end-counts'
    | '/dashboard/inventory/new'
    | '/dashboard/charts'
    | '/dashboard/inventory'
    | '/dashboard/inventory/request-queue/$id'
    | '/dashboard/inventory/request-queue'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/dashboard'
    | '/charts/$sectorId'
    | '/(auth)/(routes)/forgot-password'
    | '/(auth)/(routes)/login'
    | '/(auth)/(routes)/reset-password'
    | '/dashboard/(routes)/brochure'
    | '/dashboard/(routes)/brochure-types'
    | '/dashboard/(routes)/customers'
    | '/dashboard/(routes)/locations'
    | '/dashboard/(routes)/reports'
    | '/dashboard/(routes)/settings'
    | '/dashboard/(routes)/users'
    | '/dashboard/(routes)/warehouses'
    | '/dashboard/(routes)/'
    | '/dashboard/(routes)/inventory/$id'
    | '/dashboard/(routes)/inventory/intake-request'
    | '/dashboard/(routes)/inventory/month-end-counts'
    | '/dashboard/(routes)/inventory/new'
    | '/dashboard/(routes)/charts/'
    | '/dashboard/(routes)/inventory/'
    | '/dashboard/(routes)/inventory/request-queue/$id'
    | '/dashboard/(routes)/inventory/request-queue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ChartsSectorIdRoute: typeof ChartsSectorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts/$sectorId': {
      id: '/charts/$sectorId'
      path: '/charts/$sectorId'
      fullPath: '/charts/$sectorId'
      preLoaderRoute: typeof ChartsSectorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/(routes)/': {
      id: '/dashboard/(routes)/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardroutesIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/warehouses': {
      id: '/dashboard/(routes)/warehouses'
      path: '/warehouses'
      fullPath: '/dashboard/warehouses'
      preLoaderRoute: typeof DashboardroutesWarehousesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/users': {
      id: '/dashboard/(routes)/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof DashboardroutesUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/settings': {
      id: '/dashboard/(routes)/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardroutesSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/reports': {
      id: '/dashboard/(routes)/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardroutesReportsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/locations': {
      id: '/dashboard/(routes)/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof DashboardroutesLocationsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/customers': {
      id: '/dashboard/(routes)/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardroutesCustomersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/brochure-types': {
      id: '/dashboard/(routes)/brochure-types'
      path: '/brochure-types'
      fullPath: '/dashboard/brochure-types'
      preLoaderRoute: typeof DashboardroutesBrochureTypesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/brochure': {
      id: '/dashboard/(routes)/brochure'
      path: '/brochure'
      fullPath: '/dashboard/brochure'
      preLoaderRoute: typeof DashboardroutesBrochureRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/(routes)/reset-password': {
      id: '/(auth)/(routes)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authroutesResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/login': {
      id: '/(auth)/(routes)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authroutesLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/(routes)/forgot-password': {
      id: '/(auth)/(routes)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authroutesForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/dashboard/(routes)/inventory/': {
      id: '/dashboard/(routes)/inventory/'
      path: '/inventory'
      fullPath: '/dashboard/inventory/'
      preLoaderRoute: typeof DashboardroutesInventoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/charts/': {
      id: '/dashboard/(routes)/charts/'
      path: '/charts'
      fullPath: '/dashboard/charts/'
      preLoaderRoute: typeof DashboardroutesChartsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/inventory/new': {
      id: '/dashboard/(routes)/inventory/new'
      path: '/inventory/new'
      fullPath: '/dashboard/inventory/new'
      preLoaderRoute: typeof DashboardroutesInventoryNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/inventory/month-end-counts': {
      id: '/dashboard/(routes)/inventory/month-end-counts'
      path: '/inventory/month-end-counts'
      fullPath: '/dashboard/inventory/month-end-counts'
      preLoaderRoute: typeof DashboardroutesInventoryMonthEndCountsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/inventory/intake-request': {
      id: '/dashboard/(routes)/inventory/intake-request'
      path: '/inventory/intake-request'
      fullPath: '/dashboard/inventory/intake-request'
      preLoaderRoute: typeof DashboardroutesInventoryIntakeRequestRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/inventory/$id': {
      id: '/dashboard/(routes)/inventory/$id'
      path: '/inventory/$id'
      fullPath: '/dashboard/inventory/$id'
      preLoaderRoute: typeof DashboardroutesInventoryIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/inventory/request-queue/': {
      id: '/dashboard/(routes)/inventory/request-queue/'
      path: '/inventory/request-queue'
      fullPath: '/dashboard/inventory/request-queue/'
      preLoaderRoute: typeof DashboardroutesInventoryRequestQueueIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/(routes)/inventory/request-queue/$id': {
      id: '/dashboard/(routes)/inventory/request-queue/$id'
      path: '/inventory/request-queue/$id'
      fullPath: '/dashboard/inventory/request-queue/$id'
      preLoaderRoute: typeof DashboardroutesInventoryRequestQueueIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authroutesForgotPasswordRoute: typeof authroutesForgotPasswordRoute
  authroutesLoginRoute: typeof authroutesLoginRoute
  authroutesResetPasswordRoute: typeof authroutesResetPasswordRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authroutesForgotPasswordRoute: authroutesForgotPasswordRoute,
  authroutesLoginRoute: authroutesLoginRoute,
  authroutesResetPasswordRoute: authroutesResetPasswordRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardroutesBrochureRoute: typeof DashboardroutesBrochureRoute
  DashboardroutesBrochureTypesRoute: typeof DashboardroutesBrochureTypesRoute
  DashboardroutesCustomersRoute: typeof DashboardroutesCustomersRoute
  DashboardroutesLocationsRoute: typeof DashboardroutesLocationsRoute
  DashboardroutesReportsRoute: typeof DashboardroutesReportsRoute
  DashboardroutesSettingsRoute: typeof DashboardroutesSettingsRoute
  DashboardroutesUsersRoute: typeof DashboardroutesUsersRoute
  DashboardroutesWarehousesRoute: typeof DashboardroutesWarehousesRoute
  DashboardroutesIndexRoute: typeof DashboardroutesIndexRoute
  DashboardroutesInventoryIdRoute: typeof DashboardroutesInventoryIdRoute
  DashboardroutesInventoryIntakeRequestRoute: typeof DashboardroutesInventoryIntakeRequestRoute
  DashboardroutesInventoryMonthEndCountsRoute: typeof DashboardroutesInventoryMonthEndCountsRoute
  DashboardroutesInventoryNewRoute: typeof DashboardroutesInventoryNewRoute
  DashboardroutesChartsIndexRoute: typeof DashboardroutesChartsIndexRoute
  DashboardroutesInventoryIndexRoute: typeof DashboardroutesInventoryIndexRoute
  DashboardroutesInventoryRequestQueueIdRoute: typeof DashboardroutesInventoryRequestQueueIdRoute
  DashboardroutesInventoryRequestQueueIndexRoute: typeof DashboardroutesInventoryRequestQueueIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardroutesBrochureRoute: DashboardroutesBrochureRoute,
  DashboardroutesBrochureTypesRoute: DashboardroutesBrochureTypesRoute,
  DashboardroutesCustomersRoute: DashboardroutesCustomersRoute,
  DashboardroutesLocationsRoute: DashboardroutesLocationsRoute,
  DashboardroutesReportsRoute: DashboardroutesReportsRoute,
  DashboardroutesSettingsRoute: DashboardroutesSettingsRoute,
  DashboardroutesUsersRoute: DashboardroutesUsersRoute,
  DashboardroutesWarehousesRoute: DashboardroutesWarehousesRoute,
  DashboardroutesIndexRoute: DashboardroutesIndexRoute,
  DashboardroutesInventoryIdRoute: DashboardroutesInventoryIdRoute,
  DashboardroutesInventoryIntakeRequestRoute:
    DashboardroutesInventoryIntakeRequestRoute,
  DashboardroutesInventoryMonthEndCountsRoute:
    DashboardroutesInventoryMonthEndCountsRoute,
  DashboardroutesInventoryNewRoute: DashboardroutesInventoryNewRoute,
  DashboardroutesChartsIndexRoute: DashboardroutesChartsIndexRoute,
  DashboardroutesInventoryIndexRoute: DashboardroutesInventoryIndexRoute,
  DashboardroutesInventoryRequestQueueIdRoute:
    DashboardroutesInventoryRequestQueueIdRoute,
  DashboardroutesInventoryRequestQueueIndexRoute:
    DashboardroutesInventoryRequestQueueIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ChartsSectorIdRoute: ChartsSectorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
