/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocationLocationIdRouteImport } from './routes/location.$locationId'

const LocationLocationIdRoute = LocationLocationIdRouteImport.update({
  id: '/location/$locationId',
  path: '/location/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/location/$locationId': typeof LocationLocationIdRoute
}
export interface FileRoutesByTo {
  '/location/$locationId': typeof LocationLocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/location/$locationId': typeof LocationLocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/location/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to: '/location/$locationId'
  id: '__root__' | '/location/$locationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LocationLocationIdRoute: typeof LocationLocationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LocationLocationIdRoute: LocationLocationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
